version: '3.8'

networks:
  sync:
    driver: bridge

services:

  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - sync
    depends_on:
      - redis
    command: go run main.go -b 0.0.0.0

  redis:
    image: 'redislabs/redisearch:latest'
    container_name: "redis"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - sync
